config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
 
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do 
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      post 'users/login' => 'users#login'
      post 'users/signup' => 'users#signup'
      get  'users/:user_id/posts' => 'posts#users_posts'
      get  'users/:user_id/posts/:post_id/comments' => 'posts#list_comments'
      post 'users/posts/:post_id/addcomment' => 'posts#add_comment'
      resources :users, only: [:index, :show]
    end
  end

end

app/views/shared/_comments.html.erb
<div class='div-comments'>
  <% if post.comments_counter != 0  %>
    COMMENTS:
    <% post.five_recent_comments(post.id).each do |comment| %>
      <div class='comments'>
          * <%= User.find_by(id: comment.user_id).name %>: <%= comment.text %>      
      </div>
      
      <% if can? :destroy, comment %>
        <%= button_to "Delete Comment", user_post_comment_path(@user, post, comment), method: :delete  %>
      <% end %>

    <% end %>        
  <% end %>  
</div>

app/views/shared/_post.html.erb
<div class="post_header">
  
    <div class="ps-name">
    <%= link_to user_post_path(user_id: post.author, id: post.id) do %>
      <%= post.created_at.localtime.to_fs(:short) %>    
    <% end %>
    </div>  
    <b><%= post.title %></b>
    <p><%= post.text %></p>
    <div class="ps-counters1">
      Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %>
    </div>
  
</div>

app/views/shared/_user.html.erb
<div class='user_box' >
  <div class='user_photo'>        
      <%= image_tag( 'user.png', size: "50x50", :alt => 'User: ' + user.name.to_s  ) -%>
  </div>
  <div class='user_namePost'>
      <div class='user_name'>
        <h1><%= link_to user.name, user %></h1>
      </div>
        <div class="user_numOfPosts"
      <p>Number of posts: <%= user.posts_counter %></p>
      </div>
  </div>
</div>