config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
 
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do 
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      post 'users/login' => 'users#login'
      post 'users/signup' => 'users#signup'
      get  'users/:user_id/posts' => 'posts#users_posts'
      get  'users/:user_id/posts/:post_id/comments' => 'posts#list_comments'
      post 'users/posts/:post_id/addcomment' => 'posts#add_comment'
      resources :users, only: [:index, :show]
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  # Title must not be blank and must not exceed 250 characters.
  validates :title, presence: true, length: { minimum: 1, maximum: 250 }

  # CommentsCounter must be an integer greater than or equal to zero
  # LikesCounter must be an integer greater than or equal to zero.
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter
  after_destroy :decrement_posts_counter

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  # method that decrements the posts counter when a post it's deleted
  def decrement_posts_counter
    author.decrement!(:posts_counter)
  end

  # method which returns the 5 most recent comments for a given post.
  def five_recent_comments(_post_num)
    comments.order(updated_at: :desc).limit(5)
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApiController
      before_action :authorize_request

      def list_comments
        user_id = params[:user_id]
        post_id = params[:post_id]
        if user_id && post_id
          comments = Comment.where(user_id:, post_id:)
          render json: { status: 'SUCCESS', message: 'Loaded comments successfully', data: comments },
                 status: :ok
        else
          render json: { status: 'ERROR', message: 'User or post not found' }, status: :not_found
        end
      end

      def add_comment
        user_id = current_user.id
        text = params[:text]
        post_id = params[:post_id]
        if user_id && text && post_id
          comment = Comment.new(user_id:, text:, post_id:)
          if comment.save
            render json: { status: 'SUCCESS', message: 'Saved comment successfully', data: comment },
                   status: :ok
          else
            render json: { status: 'ERROR', message: 'Comment not saved', data: comment.errors },
                   status: :unprocessable_entity
          end
        else
          render json: { status: 'ERROR', message: 'Parameters incomplete' }, status: :not_found
        end
      end

      def users_posts
        user_id = params[:user_id]
        @user = User.find(user_id)
        if user_id && @user
          posts = Post.where(user_id:)
          render json: { status: 'SUCCESS', message: 'Loaded posts successfully', data: posts },
                 status: :ok
        else
          render json: { status: 'ERROR', message: 'User not found' }, status: :not_found
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_vars, only: %i[show index new]

  def index; end

  def show; end

  def new
    @new_post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.author = User.find_by!(id: params[:user_id])
    # debugger
    if post.save
      redirect_to user_posts_url, notice: 'Post created !'
    else
      redirect_to new_user_post_url, alert: 'Error: post not created'
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      flash[:success] = 'Post deleted !'
    else
      flash[:error] = 'Error: Post not deleted'
    end
    redirect_to user_posts_url
  end

  private

  Post.where(author: self).order(id: :asc).limit(3)
  def set_vars
    @user = User.find_by!(id: params[:user_id]) if params[:user_id]
    @posts = Post.includes([:author]).where(user_id: params[:user_id]).order(updated_at: :desc) if params[:user_id]
    @post = Post.find_by!(id: params[:id], user_id: params[:user_id]) if params[:id] && params[:user_id]
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<%= render partial: "shared/user", locals: {user: @user } %>

<% flash.each do |key, value| %>
  <span class='flash_<%= key %>'><%= value %></span>
<% end %> 

<% @posts.each_with_index  do |post, index| %>
  
    <%= render partial: "shared/post", locals: {post: post, index: index } %>  

    <%= render partial: "shared/comments", locals: {post: post, index: index } %>  
<% end %>

<div class='user_button'>
  <button>
    <%= link_to "See all users", users_path %>
  </button>

  <% if can? :manage, @post %>
    <button>
      <%= link_to "Add a post",new_user_post_path(@user) %>
    </button>
  <% end %>
  
</div>

<%= link_to 'Back' , @user %>

<% if false %>    
<% end %>

app/views/posts/new.html.erb
<h1>New Post of <%= @user.name %></h1>
<%= form_with model: @new_post, url: user_posts_path do |form|  %>
  <div>
    <label>Title</label>
    <%= form.text_field :title %>
  </div>

  <div>
    <label>Text</label>
    <%= form.text_area :text, rows: "5" %>
  </div>

  <div>
    <%= form.button "Submit Post", type: "submit" %>
  </div>
<% end %>

<%= link_to "Cancel", :back %>

app/views/posts/show.html.erb
<div class="ps-name">
    Post by <%= @user.name %>
</div>
<%= render partial: "shared/post", locals: {post: @post, index: 1 } %>  

<%= form_with model: @like, url: user_post_likes_path(@user, @post) do |form| %>
  <div>
    <%= form.button "Add a like !", type: "submit" %>
  </div>
<% end %>

<% flash.each do |key, value| %>
  <span class='flash_<%= key %>'><%= value %></span>
<% end %> 

<%= render partial: "shared/comments", locals: {post: @post, user: @user } %>

<button>
  <%= link_to 'Add a Comment', new_user_post_comment_path(@user, @post) %>
</button>

<% if can? :destroy, @post %>
  <%= button_to "Delete Post", user_post_path, method: :delete %>
<% end %>

<%= link_to "Back to Posts", user_posts_path(@user) %>